pull_request_rules:

  - name: Automatic squash merge when approved
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "base=gh-pages"
      - '-title~=(?i)\bWIP\b'
    actions:
      merge:
        strict: "smart"
        method: squash
        commit_message: "title+body"

  - name: Delete head branch after merge
    conditions:
      - "merged"
    actions:
      delete_head_branch: {}

  - name: Add label `Area-Content`
    conditions:
      - "files=index.md"
    actions:
      label:
        add: ["Area-Content"]

  - name: Add label `Area-WebPageDesign`
    conditions:
      - 'files~=(?i)\.(css|html|htm|js)$'
    actions:
      label:
        add: ["Area-WebPageDesign"]

  - name: Request a review from the owner because it is a `[MEGA]` (complex) PR
    conditions:
      - 'title~=(?i)\[MEGA\]'
    actions:
      request_reviews:
        users: ["TieBaMma"]

  - name: Assign the author because it is a draft PR
    conditions:
      - "draft"
    actions:
      assign:
        users: ["{{author}}"]

  - name: Assign the author because its title contains `WIP`
    conditions:
      - 'title~=(?i)\bWIP\b'
    actions:
      assign:
        users: ["{{author}}"]

  - name: Ask to remove `WIP` from title before merge
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "base=gh-pages"
      - 'title~=(?i)\bWIP\b'
    actions:
      comment:
        message: |
          此 pull request 似乎已经准备就绪，但 title 中仍然有 `WIP` 字样。
          如果这是笔误，请修正。
          谢谢。

  - name: (Test Env) AutoApprove # For test ONLY! Do not use in production!
    conditions:
      - "label=AutoApprove"
    actions:
      review:
        type: "APPROVE"pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
