pull_request_rules:
  - name: Automatic squash merge when approved
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "base=gh-pages"
      - '-title~=(?i)\bWIP\b'
    actions:
      merge:
        strict: "smart"
        method: squash
        commit_message: "title+body"

  - name: Add label `DuplicateOrInvalid` when abandoned
    conditions:
      - "closed"
      - "-merged"

    actions:
      label:
        add: ["DuplicateOrInvalid"]

  - name: Add label `Area-Content`
    conditions:
      - 'files~=(?i)^(?!\.|CODE_OF_CONDUCT|docs|LICENSE|README).*\.md$' # To avoid false positives, only matches a few kinds of Markdown files. False negatives can be corrected by humans, but false positives cannot!
    actions:
      label:
        add: ["Area-Content"]

  - name: Add label `Area-WebPageDesign`
    conditions:
      - 'files~=(?i)(^_.*(?<!\.md)$)|(\.(css|js|less|scss)$)' # Not all. Only the most frequently modified files.
    actions:
      label:
        add: ["Area-WebPageDesign"]

  - name: Stale PR
    conditions:
      - "label=Needs-Feedback"
      - "-draft"
    actions:
      assign:
        users: ["{{author}}"]
      request_reviews:
        users: ["TieBaMma"]

  - name: Assign the author because it is a draft PR
    conditions:
      - "draft"
    actions:
      assign:
        users: ["{{author}}"]

  - name: Assign the author because its title contains `WIP`
    conditions:
      - 'title~=(?i)\bWIP\b'
    actions:
      assign:
        users: ["{{author}}"]

  - name: Ask to remove `WIP` from title before merge
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "base=gh-pages"
      - 'title~=(?i)\bWIP\b'
    actions:
      comment:
        message: |
          此 pull request 似乎已经准备就绪，但 title 中仍然有 `WIP` 字样。
          如果这是笔误，请修正。
          谢谢。

  # - name: (Test Env) AutoApprove # For test ONLY! Do not use in production!
  #   conditions:
  #     - "label=AutoApprove"
  #   actions:
  #     review:
  #       type: "APPROVE"
